baseURL = "https://ecstatic-fermi-801e5a.netlify.app/"
languageCode = "en-us"
title = "Kim Schlesinger"
theme = "hugo-theme-pixyll"
enableRobotsTXT = true


[params]
  twitter_username = "kimschles"

